"""Trio BASIC and CSV export for converted dual-axis CAMBOX profiles."""

from __future__ import annotations

import csv
from io import StringIO

from .domain import ConvertedProfile


def _fmt(value: float, decimals: int = 6) -> str:
    rendered = f"{float(value):.{decimals}f}".rstrip("0").rstrip(".")
    return rendered if rendered not in {"", "-0"} else "0"


def _table_lines(start: int, values: tuple[int, ...], per_line: int) -> list[str]:
    lines: list[str] = []
    for offset in range(0, len(values), per_line):
        chunk = values[offset : offset + per_line]
        lines.append(f"TABLE({start + offset}, {', '.join(str(value) for value in chunk)})")
    return lines


def emit_trio_basic(profile: ConvertedProfile) -> str:
    cfg = profile.config
    diag = profile.diagnostics
    link_options = 8194  # absolute start on master DPOS; no repeat
    c_start_user_units = diag.c_start_deg / cfg.c_user_unit_deg
    c_speed_user_units = cfg.c_preposition_speed_deg_s / cfg.c_user_unit_deg
    c_accel_user_units = cfg.c_preposition_accel_deg_s2 / cfg.c_user_unit_deg
    c_decel_user_units = cfg.c_preposition_decel_deg_s2 / cfg.c_user_unit_deg

    lines = [
        f"' {cfg.program_name}",
        "' Generated by Profile CAMBOX Generator",
        f"' Source: {profile.source.source_path.name}",
        f"' {diag.sample_count} points, {diag.sample_interval_s:.6f} s sample interval",
        f"' Master: {diag.link_distance_mm:.6f} mm at {cfg.master_speed_mm_s:.6f} mm/s",
        "' One-shot profile: automatic CAMBOX repeat is intentionally disabled.",
        "' Verify homing, drive limits, directions, and emergency-stop behavior before running.",
        f"' ATYPE AXIS({cfg.master_axis})=0 belongs in MC_CONFIG; this runtime program does not change ATYPE.",
        "",
        f"y_ax = {cfg.y_axis}",
        f"c_ax = {cfg.c_axis}",
        f"master_ax = {cfg.master_axis}",
        f"profile_link_dist = {_fmt(diag.link_distance_mm)}",
        f"profile_start = {_fmt(diag.profile_start_master_mm)}",
        f"link_options = {link_options}",
        "",
        "' Stop only the axes owned by this profile program.",
        f"CANCEL(2) AXIS({cfg.y_axis})",
        f"CANCEL(2) AXIS({cfg.c_axis})",
        f"CANCEL(2) AXIS({cfg.master_axis})",
        f"WAIT IDLE AXIS({cfg.y_axis})",
        f"WAIT IDLE AXIS({cfg.c_axis})",
        f"WAIT IDLE AXIS({cfg.master_axis})",
        "",
        "' Virtual master configuration (millimetres).",
        f"BASE({cfg.master_axis})",
        "SERVO = ON",
        f"UNITS = {_fmt(cfg.master_units_counts_per_mm, 9)}",
        f"SPEED = {_fmt(cfg.master_speed_mm_s)}",
        f"ACCEL = {_fmt(cfg.master_accel_mm_s2)}",
        f"DECEL = {_fmt(cfg.master_decel_mm_s2)}",
        "DEFPOS(0)",
        "WAIT UNTIL OFFPOS = 0",
        "",
        "' Y axis configuration (millimetres).",
        f"BASE({cfg.y_axis})",
        "SERVO = ON",
        f"UNITS = {_fmt(cfg.y_units_counts_per_mm, 9)}",
        f"SPEED = {_fmt(cfg.y_preposition_speed_mm_s)}",
        f"ACCEL = {_fmt(cfg.y_preposition_accel_mm_s2)}",
        f"DECEL = {_fmt(cfg.y_preposition_decel_mm_s2)}",
        "",
        "' C axis configuration (0.1 degree user units by default).",
        f"BASE({cfg.c_axis})",
        "SERVO = ON",
        f"UNITS = {_fmt(cfg.c_units_counts_per_user_unit, 9)}",
        f"REP_DIST = {_fmt(cfg.c_full_revolution_user_units)}",
        f"SPEED = {_fmt(c_speed_user_units)}",
        f"ACCEL = {_fmt(c_accel_user_units)}",
        f"DECEL = {_fmt(c_decel_user_units)}",
        "",
        f"' Y CAMBOX raw-count table: TABLE({cfg.y_table_start}..{diag.y_table_end})",
    ]
    lines.extend(_table_lines(cfg.y_table_start, profile.y_table_values, cfg.values_per_table_line))
    lines.extend(["", f"' C CAMBOX raw-count table: TABLE({cfg.c_table_start}..{diag.c_table_end})"])
    lines.extend(_table_lines(cfg.c_table_start, profile.c_table_values, cfg.values_per_table_line))
    lines.extend([
        "",
        "' Preposition both slave axes at the first absolute CSV sample.",
        f"MOVEABS({_fmt(diag.y_start_mm, 9)}) AXIS({cfg.y_axis})",
        f"MOVEABS({_fmt(c_start_user_units, 9)}) AXIS({cfg.c_axis})",
        f"WAIT IDLE AXIS({cfg.y_axis})",
        f"WAIT IDLE AXIS({cfg.c_axis})",
        "",
        "' Arm separate CAMBOX moves at the same future absolute master DPOS.",
        f"CAMBOX({cfg.y_table_start}, {diag.y_table_end}, 1, profile_link_dist, master_ax, link_options, profile_start) AXIS({cfg.y_axis})",
        f"WAIT LOADED AXIS({cfg.y_axis})",
        f"CAMBOX({cfg.c_table_start}, {diag.c_table_end}, 1, profile_link_dist, master_ax, link_options, profile_start) AXIS({cfg.c_axis})",
        f"WAIT LOADED AXIS({cfg.c_axis})",
        "",
        "' Accelerate before profile_start, then execute the profile at constant master speed.",
        f"FORWARD AXIS({cfg.master_axis})",
        f"WAIT IDLE AXIS({cfg.y_axis})",
        f"WAIT IDLE AXIS({cfg.c_axis})",
        f"CANCEL AXIS({cfg.master_axis})",
        f"WAIT IDLE AXIS({cfg.master_axis})",
        "STOP",
    ])
    return "\n".join(lines) + "\n"


def emit_points_csv(profile: ConvertedProfile) -> str:
    output = StringIO(newline="")
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow([
        "index", "time_s", "master_mm", "y_absolute_mm", "y_relative_mm", "y_table_counts",
        "c_absolute_rad", "c_absolute_deg", "c_relative_deg", "c_relative_0.1deg", "c_table_counts",
    ])
    for point in profile.points:
        writer.writerow([
            point.index,
            f"{point.time_s:.12g}",
            f"{point.master_mm:.12g}",
            f"{point.y_absolute_mm:.12g}",
            f"{point.y_relative_mm:.12g}",
            point.y_counts,
            f"{point.c_absolute_rad:.12g}",
            f"{point.c_absolute_deg:.12g}",
            f"{point.c_relative_deg:.12g}",
            f"{point.c_relative_user_units:.12g}",
            point.c_counts,
        ])
    return output.getvalue()
