"""Plain-language help for the standalone CAMBOX settings."""

SETTING_HELP = {
    "demo_y_preposition": "Simulation demo: emit DEFPOS at the first Y position minus 5 mm, then MOVEABS to that first position. This resets the coordinate datum without moving the axis. Leave off for normal machine positioning.",
    "demo_c_preposition": "Simulation demo: emit DEFPOS at the first C angle minus 5 output degrees, then MOVEABS to that angle. Automatically converts to C user units. This resets the coordinate datum without moving the axis. Leave off for normal machine positioning.",
    "time_column": "Enter the name of the time column in your CSV, for example 'temps'. Values must be in seconds and evenly spaced. The first row is the start of the movement.",
    "y_column": "Enter the name of the column containing Y positions, for example 'Y'. Values must be in millimetres. Y moves to the first position before the profile starts.",
    "c_column": "Enter the name of the column containing C angles, for example 'C'. Values must be in radians. The app converts them to degrees for you.",
    "unwrap_c_axis": "Use this when angles wrap around: for example, 179° followed by −179° should mean a small 2° turn. Turn it off if the large turn is intentional.",
    "y_axis": "The controller's axis number for the Y movement. Your setup uses 0. Y, C and the master must each have a different number.",
    "c_axis": "The controller's axis number for C rotation. Your setup uses 1. Y, C and the master must each have a different number.",
    "master_axis": "The controller's axis number for the virtual master, which keeps Y and C moving together. Your setup uses 10. This axis must already be configured as virtual on the controller.",
    "invert_y": "Make Y move in the opposite direction after reaching its starting position. For example, a move of +10 mm becomes −10 mm. The starting position stays the same.",
    "invert_c": "Make C turn in the opposite direction after reaching its starting angle. For example, a turn of +30° becomes −30°. The starting angle stays the same.",
    "master_encoder_counts_per_rev": "Position counts for one virtual master turn. This is an independent software scale; it does not need to match either motor encoder. Regeneration preserves the CSV duration.",
    "master_travel_per_rev_mm": "How many millimetres one virtual master turn represents. Your setup uses 4 mm per turn. Used together with counts/rev to calculate position scaling.",
    "y_encoder_counts_per_rev": "Effective controller counts per motor revolution after drive electronic gearing. Confirm counts per revolution, not the maximum encoder value: a range 0–65535 contains 65536 counts. The drive and any external model must use matching scaling.",
    "y_travel_per_rev_mm": "Screw lead: millimetres travelled per screw revolution, before gearing. For a 10 mm screw enter 10. The Y gear ratio is applied separately; do not divide the lead by it.",
    "y_gear_ratio": "Enter motor turns in the left field and screw turns in the right field. Use 1 : 1 for direct drive. With a 10 mm screw and 2 : 1 gearing, Y travels 5 mm per motor turn. Both numbers must be positive.",
    "c_gear_ratio": "Enter motor turns in the left field and blade turns in the right field. Use 10 : 1 for a 10:1 reduction (36 degrees of blade rotation per motor turn), or 1 : 1 for direct drive. Both numbers must be positive.",
    "c_encoder_counts_per_rev": "Effective controller counts per motor revolution after drive electronic gearing. Confirm counts per revolution, not the maximum encoder value. The drive and any external model must use matching scaling.",
    "c_degrees_per_rev": "Output rotation per motor revolution: 360° for direct drive, 36° for a 10:1 reduction gearbox. This sets mechanical scaling independently of the C user unit.",
    "c_wrap_distance_deg": "Symmetric C position boundary in output degrees (REP_OPTION=0): positions wrap at ± this angle. Independent of gearing. Choose a boundary larger than every commanded angle in the unwrapped one-shot profile, including its starting position.",
    "c_user_unit_deg": "How many degrees the controller should mean by '1' on C. Enter 0.1 for tenths of a degree: a 90° turn is then written as 900 in the program. Enter 1 to use degrees as the unit.",
    "master_speed_mm_s": "Speed of the virtual master in millimetres per second. At 80, one second of CSV motion covers 80 mm of master travel. Changing this and generating again keeps the movement duration from your CSV.",
    "master_accel_mm_s2": "How quickly the master reaches its running speed. A larger number reaches speed sooner. The app calculates enough run-up distance before starting the Y/C profile.",
    "master_decel_mm_s2": "How quickly the master slows to a stop after the Y/C movement finishes. A larger number stops it more quickly.",
    "lead_margin_mm": "Extra distance the master travels at full speed before Y and C begin their profile. For example, 1 adds another 1 mm after the run-up.",
    "y_preposition_speed_mm_s": "How fast Y moves to its starting position, in mm per second. This applies only to getting ready; the CSV determines Y speed during the profile.",
    "y_preposition_accel_mm_s2": "How quickly Y speeds up while moving to its starting position. A larger number gives a sharper start. This applies only to the preparation move.",
    "y_preposition_decel_mm_s2": "How quickly Y slows down as it reaches its starting position. A larger number gives a sharper stop. This applies only to the preparation move.",
    "c_preposition_speed_deg_s": "How fast C turns to its starting angle, in degrees per second. Enter degrees even if the controller uses 0.1° units. The CSV determines C speed during the profile.",
    "c_preposition_accel_deg_s2": "How quickly C speeds up while turning to its starting angle. A larger number gives a sharper start. Enter degrees/s²; the app handles the controller conversion.",
    "c_preposition_decel_deg_s2": "How quickly C slows down as it reaches its starting angle. A larger number gives a sharper stop. Enter degrees/s²; the app handles the controller conversion.",
    "y_table_start": "Where to start storing Y movement points in the controller's TABLE memory. For example, 100 points starting at 1000 use slots 1000–1099. Keep these slots separate from C.",
    "c_table_start": "Where to start storing C movement points in the controller's TABLE memory. For example, 100 points starting at 3000 use slots 3000–3099. Keep these slots separate from Y.",
    "table_size": "How many TABLE memory slots your controller has. The app checks that both sets of points fit. Entering a larger number here does not add memory to the controller.",
    "values_per_table_line": "How many movement points to put on each line of the generated program. Use 8 for shorter lines or up to 16 for fewer lines. The movement itself stays the same.",
    "time_uniformity_tolerance_pct": "How much variation is allowed between CSV time steps. For example, 1% allows a typical 4 ms step to range from 3.96 to 4.04 ms. If the variation is larger, generation stops so you can correct the CSV.",
    "program_name": "Choose a name for the exported program and point files, for example 'my_profile'. This name also appears at the top of the generated program.",
}
